#!/bin/bash

echo "=== REMOVENDO ASSETS NÃO UTILIZADOS ==="
echo ""

# Bibliotecas não utilizadas
UNUSED_LIBS=(
  "apexcharts"
  "bootstrap-datepicker"
  "bootstrap-editable"
  "bootstrap-filestyle2"
  "bootstrap-maxlength"
  "bootstrap-rating"
  "bootstrap-timepicker"
  "bootstrap-touchspin"
  "chance"
  "chart.js"
  "datatables.net"
  "datatables.net-autofill"
  "datatables.net-autofill-bs4"
  "datatables.net-autofill-bs5"
  "datatables.net-buttons"
  "datatables.net-buttons-bs4"
  "datatables.net-buttons-bs5"
  "datatables.net-colreorder"
  "datatables.net-colreorder-bs4"
  "datatables.net-colreorder-bs5"
  "datatables.net-fixedcolumns"
  "datatables.net-fixedcolumns-bs4"
  "datatables.net-fixedcolumns-bs5"
  "datatables.net-fixedheader"
  "datatables.net-fixedheader-bs4"
  "datatables.net-fixedheader-bs5"
  "datatables.net-keytable"
  "datatables.net-keytable-bs4"
  "datatables.net-keytable-bs5"
  "datatables.net-responsive"
  "datatables.net-responsive-bs4"
  "datatables.net-responsive-bs5"
  "datatables.net-rowgroup"
  "datatables.net-rowgroup-bs4"
  "datatables.net-rowgroup-bs5"
  "datatables.net-rowreorder"
  "datatables.net-rowreorder-bs4"
  "datatables.net-rowreorder-bs5"
  "datatables.net-scroller"
  "datatables.net-scroller-bs4"
  "datatables.net-scroller-bs5"
  "datatables.net-select"
  "datatables.net-select-bs4"
  "datatables.net-select-bs5"
)

echo "Removendo bibliotecas não utilizadas..."
for lib in "${UNUSED_LIBS[@]}"; do
  if [ -d "public/assets/libs/$lib" ]; then
    rm -rf "public/assets/libs/$lib"
    echo "✓ Removido: public/assets/libs/$lib"
  fi
done

echo ""
echo "Removendo arquivos JS de páginas não utilizadas..."

# Arquivos JS em pages/ que não estão referenciados
JS_FILES=(
  "apexcharts.init.js"
  "calendar.init.js"
  "calendars.js"
  "chartjs.init.js"
  "coming-soon.init.js"
  "crypto-dashboard.init.js"
  "crypto-exchange.init.js"
  "crypto-kyc-app.init.js"
  "crypto-orders.init.js"
  "crypto-wallet.init.js"
  "dashboard.init.js"
  "dashboard-blog.init.js"
  "datatables.init.js"
  "echarts.init.js"
  "ecommerce-cart.init.js"
  "ecommerce-select2.init.js"
  "email-editor.init.js"
  "file-manager.init.js"
  "flot.init.js"
  "fontawesome.init.js"
  "form-advanced.init.js"
  "form-editor.init.js"
  "form-mask.init.js"
  "form-repeater.int.js"
  "form-validation.init.js"
  "form-wizard.init.js"
  "form-xeditable.init.js"
  "gmaps.init.js"
  "ico-landing.init.js"
  "jquery-knob.init.js"
  "leaflet-map.init.js"
  "leaflet-us-states.js"
  "lightbox.init.js"
  "materialdesign.init.js"
  "product-filter-range.init.js"
  "profile.init.js"
  "project-overview.init.js"
  "range-sliders.init.js"
  "rating-init.js"
  "saas-dashboard.init.js"
  "schedules.js"
  "session-timeout.init.js"
  "sparklines.init.js"
  "sweet-alerts.init.js"
  "table-editable.int.js"
  "table-responsive.init.js"
  "task-create.init.js"
  "task-form.init.js"
  "task-kanban.init.js"
  "tasklist.init.js"
  "timeline.init.js"
  "toastr.init.js"
  "tui-charts.init.js"
  "vector-maps.init.js"
)

for file in "${JS_FILES[@]}"; do
  if [ -f "public/assets/js/pages/$file" ]; then
    rm "public/assets/js/pages/$file"
    echo "✓ Removido: public/assets/js/pages/$file"
  fi
done

echo ""
echo "=== RESUMO DA LIMPEZA ==="
du -sh public/assets/
echo ""
echo "✓ Limpeza concluída!"
