#!/bin/bash

# Mais bibliotecas não utilizadas que podem ser removidas
MORE_UNUSED_LIBS=(
  "admin-resources"
  "@chenfengyuan"
  "@curiosityx"
  "autocomplete"
  "autosize"
  "bacon"
  "bootstrap-fileinput"
  "bootstrap-glyphicons"
  "bootstrap-icons"
  "bootstrap-select"
  "bootstrap-slider"
  "bootstrap-switch"
  "bootstrap4-editable"
  "bootstrap-toggle"
  "bootstrap-touchspin-fork"
  "bootstrap-wizard"
  "chart"
  "chartist"
  "chartjs-plugin-datalabels"
  "chosen"
  "clockpicker"
  "cloundflare"
  "cloundflare-v2"
  "codemirror"
  "color"
  "colorpicker"
  "country-state-city"
  "css"
  "css-loader"
  "crypto-js"
  "ctrl"
  "currency"
  "cursors"
  "dashboard"
  "dashboardv1"
  "dashboardv2"
  "dashboardv3"
  "datatable"
  "daterangepicker"
  "daterangepicker-old"
  "datetimepicker"
  "datetimepicker-old"
  "datetimepicker2"
  "datetimepicker3"
  "datetimepicker4"
  "datetimepicker5"
  "datetimepicker6"
  "day-js"
  "deck.gl"
  "deepzoom"
  "deja-vu"
  "demo"
  "demos"
  "detect.js"
  "devextreme"
  "devextreme-react"
  "dhtmlx"
  "dialog"
  "diff_match_patch"
  "dnd"
  "d3"
  "d3-plugins"
  "d3-tip"
  "d3js"
  "d3-v3"
  "d3-v4"
  "d3-v5"
)

echo "Removendo mais bibliotecas não utilizadas..."
REMOVED=0
for lib in "${MORE_UNUSED_LIBS[@]}"; do
  if [ -d "public/assets/libs/$lib" ]; then
    rm -rf "public/assets/libs/$lib"
    echo "✓ Removido: public/assets/libs/$lib"
    ((REMOVED++))
  fi
done

echo ""
echo "Total de libs removidas nesta etapa: $REMOVED"
du -sh public/assets/
